  - hosts: all
    gather_facts: no
    tasks:
      - community.docker.docker_container:
          name: app
          # Обязательно указываем тег, который хотим деплоить
          # Если образа на сервере нет, Ansible его автоматически скачает
          image: "abra19/devops-example-app:latest"
          # Подключаем супервизор
          # Если контейнер остановится, например, из-за ошибок
          # супервизор Docker его перезапустит
          restart_policy: always
          # Запускаем, если не запущен
          state: started
          # Делаем доступным снаружи
          ports:
            - 3000:3000
          env: # Настраиваем
            NODE_ENV: production
            SERVER_MESSAGE: "Hello from Abra19!"